# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-19 20:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20180319_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomments',
            name='commentator',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 19, 20, 9, 41, 598060)),
        ),
    ]
