# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-19 20:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20180319_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomments',
            name='commentator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_all_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 19, 20, 20, 41, 526344)),
        ),
    ]
