# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-20 11:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20180319_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 20, 11, 58, 3, 898763)),
        ),
    ]
